# This is a workflow aimed at helping to get familiar with pull request in GitHub
name: basic-test

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events for the "assignments" branches
  pull_request:
    branches: [ "assignments" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job prepare environment and run the analysis on a test file
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      PR_TITLE: ${{ github.event.pull_request.title }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Setup GHDL environment
      - name: Setup GHDL
        uses: ghdl/setup-ghdl@v1
        with:
          version: latest # or a specific version like '2.0.0'
          # Select GHDL backend (mcode, llvm or gcc)
          backend: mcode
  
      - name: Run the test script
        run: |
          chmod +x ./run-test.sh
          ./run-test.sh
